openapi: 3.0.0
info:
  title: async serverless application gem API
  description: async serverless application gem API
  version: 1.0.0
servers:
  - url: http://localhost:{port}/gem/
    description: dev
    variables:
      port:
        default: '8081'
  - url: https://api.<domain-name>/gem/
    description: stg
security:
  - bearerAuth: []
paths:
  /v1/healthcheck:
    get:
      tags:
        - healthcheck
      summary: ヘルスチェックAPI
      description: APIが正常に動作しているかを確認します。
      operationId: healthcheck
      responses:
        '200':
          description: API is up and running
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
      security: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    HealthCheck:
      title: HealthCheck
      type: object
      description: HealthCheckのレスポンス
      required:
        - message
      properties:
        message:
          description: メッセージ。通常はok
          type: string
      example:
        message: ok
