services:
  shop-api:
    platform: linux/amd64
    image: cosmtrek/air:v1.61.7
    container_name: shop-api
    working_dir: /go/src/github.com/tamaco489/async_serverless_application_sample/api/shop
    volumes:
      - ./shop:/go/src/github.com/tamaco489/async_serverless_application_sample/api/shop
      - ~/.cache/go-build:/root/.cache/go-build
    ports:
      - "8080:8080"
    env_file:
      - ./shop/.env

  gem-api:
    platform: linux/amd64
    image: cosmtrek/air:v1.61.7
    container_name: gem-api
    working_dir: /go/src/github.com/tamaco489/async_serverless_application_sample/api/gem
    volumes:
      - ./gem:/go/src/github.com/tamaco489/async_serverless_application_sample/api/gem
      - ~/.cache/go-build:/root/.cache/go-build
    ports:
      - "8081:8080"
    env_file:
      - ./gem/.env

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./gem/docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
